# Generated by Django 4.0.4 on 2022-06-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTYapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atelier', models.CharField(max_length=40)),
                ('adress', models.CharField(max_length=80)),
            ],
        ),
    ]
