# Generated by Django 4.0.4 on 2022-06-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.CharField(max_length=40)),
                ('add_date', models.DateField()),
                ('is_available', models.BooleanField()),
            ],
        ),
    ]
